services:
  - type: web
    name: my-pnpm-app
    env: node
    plan: free
    buildCommand: "pnpm install && pnpm build"
    startCommand: "pnpm start"
    envVars:
      - key: NODE_ENV
        value: production
