services:
  - type: web
    name: angels-school
    env: node
    plan: free
    buildCommand: "pnpm install && pnpm build"
    startCommand: "pnpm start"
    envVars:
      - key: NODE_ENV
        value: production
    nodeVersion: 20
